apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy
  namespace: budgetsh
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: deploy
  namespace: budgetsh
rules:
  - apiGroups: ["extensions", "batch", ""]
    resources: ["deployments", "jobs", "ingresses", "services", "pods"]
    verbs: ["get", "list", "patch", "update", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: deploy
  namespace: budgetsh
subjects:
  - kind: ServiceAccount
    name: deploy
    namespace: budgetsh
roleRef:
  kind: Role
  name: deploy
  apiGroup: rbac.authorization.k8s.io
