name: dialyzer
on: push
jobs:
  dialyzer:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.1-slim
    steps:
      - uses: actions/checkout@v1
      - run: apt-get update && apt-get install -y build-essential
      - name: Install Dependencies
        run: |
          cd backend
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Dialyzer
        run: |
          cd backend
          mix dialyzer
