name: frontend
on:
  push:
    branches:
      - master
    paths:
      - "frontend/*"
      - "frontend/*/*"
      - "frontend/*/*/*"
      - "frontend/*/*/*/*"
      - "frontend/*/*/*/*/*"
      - "frontend/*/*/*/*/*/*"
      - "kubernetes/frontend.yaml"
      - ".github/workflows/frontend_master.yml"
jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build and Push
        run: make build-frontend push-frontend
  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image
    steps:
      - uses: actions/checkout@v1
      - uses: azure/setup-kubectl@v1
        with:
          version: v1.15.3
      - uses: azure/k8s-actions/k8s-set-context@master
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
      - name: Update SHAs
        run: |
          sed -ie "s/latest/$GITHUB_SHA/" kubernetes/frontend.yaml
      - name: Deploy
        run: "kubectl apply -f kubernetes/frontend.yaml"
      - name: Wait for completion
        run: "kubectl rollout -n budgetsh status deployment/budgetsh-frontend"
        timeout-minutes: 8
