name: budgetsh-frontend
on:
  push:
    branches:
      - master
    paths:
      - "frontend/*"
      - "frontend/*/*"
      - "frontend/*/*/*"
      - "frontend/*/*/*/*"
      - "frontend/*/*/*/*/*"
      - "frontend/*/*/*/*/*/*"
      - "kubernetes/frontend.yaml"
jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY_URL: reg.quan.io
      - name: Build and Push
        uses: actions/action-builder/docker@master
        with:
          entrypoint: make
          args: build-frontend push-frontend
  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image
    steps:
      - uses: actions/checkout@v1
      - uses: azure/k8s-actions/setup-kubectl@master
        with:
          version: v1.15.3
        env:
          RUNNER_TEMPDIRECTORY: ${RUNNER_TEMP}
          RUNNER_TOOLSDIRECTORY: ${RUNNER_TOOL_CACHE}
      - uses: azure/k8s-actions/k8s-set-context@master
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
      - name: Update SHAs
        run: |
          sed -ie "s/latest/$GITHUB_SHA/" kubernetes/frontend.yaml
      - name: Deploy
        run: "kubectl apply -f kubernetes/frontend.yaml"
      - name: Wait for completion
        run: "kubectl rollout -n budgetsh status deployment/budgetsh-frontend"
        timeout-minutes: 8
